### ISSUE TITLE
Add support for split packages

### ISSUE THREAD

**Issue by Ram-Z** [ccr-tools/aur2ccr#10]
at the very least for python packages, most of them are in a split package with

pkgbase=python-<package>
pkgname=(python2-<package> python-<package>)

**Comment by rshipp** [comment]
Not sure what this was about. aur2ccr sort-of supports split packages, and CCr doesn't. Can we close it?

**Comment by Ram-Z** [comment]
Yeah, I don't remember what the issue was.
