### ISSUE TITLE
makepkg and variables

### ISSUE THREAD

**Issue by Inkane** [ccr-tools/aur2ccr#2]
The package freeorion from AUR (http://aur.archlinux.org/packages/fr/freeorion/PKGBUILD) contains the following lines:

```
if [ "$CARCH" == "x86_64" ]
then
  depends=('lib32-nvidia-cg-toolkit')
else
  depends=('nvidia-cg-toolkit')
fi
depends=('bullet' 'freealut' 'gigi' 'libvorbis' 'python2')
```

According to my understanding, this should result in  depends containing 'bullet', 'freealut', 'gigi', 'libvorbis' and 'pyththon2', but not (lib32-)nvidia-cg-toolkit, which is probably not intended by the author. Or does makepkg some magic to join the arrays?

If not, what should aur2ccr do? Trigger a warning when variables are overwritten?

**Comment by rshipp** [comment]
Hm, that's a weird PKGBUILD. Those would need to be `depends+=('more' 'depends')` for that to work. That is something we can add to pkglint. If pkglint is just written in the same way as your parser, we can just call it from aur2ccr. That way, there is no need to write the same code twice.

**Comment by rshipp** [comment]
makepkg doesn't do anything with the depends, it is the ccr script that scrapes those. And all it does is source the PKGBUILD, which means bash takes care of everything. Those nvidia depends will just be ignored. 
Here's the relevant function in ccr:

```
scrapeccrdeps() {
  pkginfo "$1"
  . "$tmpdir/$1.PKGBUILD"
  IFS=$'\n'
  dependencies=( $(echo -e "${depends[*]}\n${makedepends[*]}" | sed -e 's/=.*//' -e 's/>.*//' -e 's/<.*//'| sort -u) )
}
```

**Comment by Inkane** [comment]
Okay, then I'll parse it just like ccr would do and add a warning later.
