### ISSUE TITLE
Unknown make error

### ISSUE THREAD

**Issue by rshipp** [ccr-tools/aur2ccr#5]
Reported by WillingMagic (output is in Polish):
http://paste.chakra-project.org/1303/

Seems to be something going wrong in getmirrors.py, but no error messages are printed, other than the generic make failure. This is on x86_64, though that shouldn't matter. I can't reproduce it here.

**Comment by Inkane** [comment]
Needs better error logging before it can be resolved. The pasted log doesn't contain useful information.

**Comment by Inkane** [comment]
Both duckduckgo and Arch changed their website. The regex is adjusted, and the countries are converted to country codes. It probably needs further testing.

**Comment by rshipp** [comment]
I think Argentina should be BR, not Brazil.

**Comment by Inkane** [comment]
Already fixed

**Comment by rshipp** [comment]
OK.

**Comment by rshipp** [comment]
Works here: http://paste.chakra-project.org/1352
I'll update the aur2ccr package on CCR. aur2ccr-git will still be broken though, until this is pushed to [master].

**Comment by rshipp** [comment]
Also, please fix the typo here: https://github.com/Inkane/aur2ccr/blob/parser/getmirrors.py#L180
That prevented it from giving us useful information.

**Comment by Inkane** [comment]
Fixed in parser and development.
