### ISSUE TITLE
Change name conversion for python packages

### ISSUE THREAD

**Issue by Inkane** [ccr-tools/aur2ccr#6]
Depending on the outcome of http://groups.google.com/group/chakra-packagers/browse_thread/thread/97acd7beb67db7ea, the name conversion rules in names.conf have to be changed. At least python2=python needs to be removed.

**Comment by rshipp** [comment]
python2=python is already removed from the stable aur2ccr package in CCR, and in the development branch on git. All python-whatever packages in the official repos will be renamed to python2-whatever ONLY when they are in need of updates. We will just need to keep track of what happens and change these rules as needed.

**Comment by Inkane** [comment]
Okay. I'd like to keep this issue open as a reminder to check for name changes.

**Comment by rshipp** [comment]
This feature is unmaintainable and is removed in 2.0; closing.
